version: '2'

services:
  web:
    build: web
    environment:
      VIRTUAL_HOST: "https://*/*, http://*/*"
      FORCE_SSL: 1
    networks:
      - backend
  webapi:
    build: webapi
    environment:
      VIRTUAL_HOST: "https://*/api, https://*/api/*"
      ASPNET_ENV: Development
      FORCE_SSL: 1
    links:
      - redis
    networks:
      - backend
  redis:
    image: anapsix/webdis
    environment:
      LOCAL_REDIS: "true"
    ports:
      - "7379:7379"
    networks:
      - backend
  lb:
    image: tutum/haproxy
    links:
      - web
      - webapi
    environment: 
      - DEFAULT_SSL_CERT=-----BEGIN CERTIFICATE-----\nMIID3zCCAsegAwIBAgIJAK8TJbM7LDUfMA0GCSqGSIb3DQEBCwUAMIGFMQswCQYD\nVQQGEwJCRTERMA8GA1UECAwIQnJ1c3NlbHMxETAPBgNVBAcMCEJydXNzZWxzMRcw\nFQYDVQQKDA5GYWJpZW4gRGVob3ByZTEUMBIGA1UEAwwLZGVob3ByZS5jb20xITAf\nBgkqhkiG9w0BCQEWEmZhYmllbkBkZWhvcHJlLmNvbTAeFw0xNjAzMDcxMzQ0NTJa\nFw0xNzAzMDcxMzQ0NTJaMIGFMQswCQYDVQQGEwJCRTERMA8GA1UECAwIQnJ1c3Nl\nbHMxETAPBgNVBAcMCEJydXNzZWxzMRcwFQYDVQQKDA5GYWJpZW4gRGVob3ByZTEU\nMBIGA1UEAwwLZGVob3ByZS5jb20xITAfBgkqhkiG9w0BCQEWEmZhYmllbkBkZWhv\ncHJlLmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAMVXSHVHRQ4p\nzfid29SsVxoWPtl+BZMVCL7N9vtajpKeIWRUkRZZJ+Bi8k/KaSHmnOKLW9FDVbsR\nI/hhC9HTwQP85gOQoKW7/JD+hlGQGZZjJTJRMtrsJ0etRt6LX0ZUzMSIfOkvyZft\ngcfrYgCBYXGUgp2c7vuccmae0z1to7LSRGEbBKbhx20KycBM/JkMVNycoFimea2h\nkQJkquNuCN/lZtzF3YbXQlaqOUCUEiyEDq+uC1sC7/Bk5Lpo/Uky9GqUAbnok62e\niayS6vfkF5f/U/qWU3o7YDXsNRBLN8RsR83phASR/4RgOZI2t3qJykbzixyX9bne\nYSM7j0p8GhcCAwEAAaNQME4wHQYDVR0OBBYEFHfOnPa1A0wKXJMN/6uE1efSOp12\nMB8GA1UdIwQYMBaAFHfOnPa1A0wKXJMN/6uE1efSOp12MAwGA1UdEwQFMAMBAf8w\nDQYJKoZIhvcNAQELBQADggEBAB7u3dZjtbFQ60L0NoI+u0adKGeEMJg59hSuOrYa\np4k/ry4+4niXOcMaiRElrS5qgFWWmmi18gFlY+H2g6eOXxRL+61iGyNJvRJg8osn\nuBJfg0jiB4d/mqFWCMBZt6A6vV9xy2BkR0VFzoJC+269UkCoMaoDRSggK0R6JsIy\nvuBmyb/XXKFssITyHQRgsk65aNKPmGVeXQoY2ED7MDPgf37vxuWzYNvAxE+KzZFA\noW8s27/QU2R/M0I3a4LA4WxX8P16H10Cjjos6184aGo0eAtS24gQIgacAfakVjdF\nf9MJ5lTm5Mt/Eu7Soqu2I5/N+BbSSlMpXuvAk34kDKDjcvU=\n-----END CERTIFICATE-----\n-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDFV0h1R0UOKc34\nndvUrFcaFj7ZfgWTFQi+zfb7Wo6SniFkVJEWWSfgYvJPymkh5pzii1vRQ1W7ESP4\nYQvR08ED/OYDkKClu/yQ/oZRkBmWYyUyUTLa7CdHrUbei19GVMzEiHzpL8mX7YHH\n62IAgWFxlIKdnO77nHJmntM9baOy0kRhGwSm4cdtCsnATPyZDFTcnKBYpnmtoZEC\nZKrjbgjf5Wbcxd2G10JWqjlAlBIshA6vrgtbAu/wZOS6aP1JMvRqlAG56JOtnoms\nkur35BeX/1P6llN6O2A17DUQSzfEbEfN6YQEkf+EYDmSNrd6icpG84scl/W53mEj\nO49KfBoXAgMBAAECggEAfR/0r3f7DxnuoV7mThjgOYg1XY4MVtAVdXX+zi0DDW/6\nWDVOsU7ie+IBJhp/QqGIhBQ8qZj6ONyLZCeUaPzM+4xVA5mmYq+pWv4niHvH3ZUL\ntrXJewoVddsmfmD8jgmitFKecPR97DkJ+wsCXrOqZ2v0zZ794Me3ud2mruJf0zdm\nDHFFvXi46tAif7TpyOvvyyHaGIq3PnThWxaOsbDCASG21r8il3ZNTSaatpjaaJwb\nuW5LAPEiLo+xunr8K8dEWliU3AeU9g3iW56KmMwEaS686R18TwEXVXkTax4s2yOk\n2b2aueFkxKn3uADMgIhNZP10F0JZvglMU7t7nvP+MQKBgQDryjwzfQy7zP0fB/Qy\nzIyrtaeZL8jdD2lI5UlpOztIiurrDQm4b9ocnLlKir9huWvO3s3cDbmM6adKJTVd\n+/o29Im3fODC4xt1joOVEOS2n8ADAm8SESKuzfm1G/QtfUgpFwgMAL8wdu8B9SE2\n6hT0JGSxgZ5LKm3Hc9YVANlvMwKBgQDWQWOm692OmooOB+jA8NkojEoymie5z/XS\nWMROaHakxRRbzD+H+h1QSZu4FR0+SJhmt5efMk1Y7LsplTv1tNKexWVi6gsypjIm\nTobDxo1AVeHbyD7hB7mLswflfkRvZA5fd3jxtzvB/dbEZav93SbRfoTjQsnzsn/5\nn/ilwSq5jQKBgFrP/Bm0iuf1znNaI+JAx9kGULN+JPWHDvzFWl3OM0oAPvQihGDl\nq3KjpfWgtI8V1ADL7StYmeM8xnKXHBPDjZ4G1te1n/dPcu724ZTS+dOgeVpvYInr\n0ZjTud3YE1ZFzzoMJcxBqWEoHWt6lr1IsKNLNQDstCOtBrTv1z8loZjjAoGBAIqT\neHS6EW7unWQ90VkZbhs/wa3A7vjLfN8z8qQUBMjFf0lwbZbxOox3T3Rck7F5Grk0\n/ahFzKk7VEKs9z8QWTm/yreTUPLNc5o7KAbwIOP/qDmS5rh9WpD0lqLkbDbvrCwr\nBdqw/MGYAJS+feOQak8NWb3zsNMiHIvD3/q1WYDxAoGBAJlWxoLltWEpRLaUiauI\nQmMkBSQK2wXF/bZYiauxdd6Xg/amHvKhHDJDIoEXEGDplL1Tdsn76fLaW9Zd3pyH\nXoxPo00vZ0QMhidDb9FIo9fjJnHcq8vf5x7OwMY5GsCHJUMULhuyqalQmM7lN3Ii\nM04G7BaosuWiRUBZHqJHZ+0B\n-----END PRIVATE KEY-----\n
      - SSL_BIND_CIPHERS=ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256
      - DEFAULT_EXTRA_SETTINGS="http-response add-header X-Frame-Options SAMEORIGIN,http-response add-header X-Xss-Protection 1;mode=block"
    ports:
      - "80:80"
      - "443:443"
    networks:
      - backend
      - frontend
networks:
  frontend: 
    driver: bridge
  backend:
    driver: bridge
